version: 2.0
orbs:
  codecov: codecov/codecov@1.0.3
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    branches:
      ignore: gh-pages
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: yarn install
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run all tests with coverage
          command: yarn test:coverage-ci
      - codecov/upload:
          file: ./packages/react-silk-ui/coverage/coverage-final.json
      - codecov/upload:
          file: ./packages/react-silk-form/coverage/coverage-final.json
      - run:
          name: Build library
          command: yarn build:lib
      - run:
          name: Build documentation page
          command: yarn build:docs
